### PR TITLE
feat: show current state using different icons

### PR DESCRIPTION
**Pull request by abeatrix**
This PR is to address the issue stated in https://github.com/sourcegraph/sourcegraph/issues/17429
The button icons will now switch color between modes to indicate different states (yellow for whole-file display, red for selected line, and black for hiding):
3states1button

### CODE REVIEW

**Review by erzhtor — APPROVED** [review]
Looks good, for sure better than the current version. 👍 

Two minor comments:
1. Maybe @jjinnii or @rrhyne could help pick icons for different states?
    1. disabled state icon
    1. enabled - show blames for a selected line(s)
    1. enabled - show blames for the entire file
1. It would be nice to rename icons according to the state they represent.

**Review by vdavid — APPROVED** [review]
Nit: the SVGs could be minified (e.g. with https://www.svgminify.com/) for a ~20% reduction in size.

**Comment by abeatrix** [comment]
@vdavid thanks, that's really helpful, saved the link for future reference too!

@erzhtor should we wait for sara and rob before shipping the changes?

**Comment by jjinnii** [comment]
Hey all! Sorry for missing this issue, I only followed the thread in Slack. 

I think there's some [unresolved discovery work ](https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1645459069529259?thread_ts=1645206986.868699&cid=C01T0BL4EFN)that needs to be done on the original user problem. Both @rrhyne and @ryankscott  share thoughts that this design isn't necessarily solving the original user problem, and I do have some concerns about the state colors (red/yellow) unintentionally sending message about a good/bad status.

Given that the git blame is a widely used extension, I'd like for prod/design to be involved in the solution before we ship any changes. We can discuss at planning, but I can potentially pull this in for the next iteration.

**Comment by abeatrix** [comment]
@jjinnii sounds good, i will leave this PR open for now then ?

**Comment by jjinnii** [comment]
Yes, thanks Beatrix. I moved the original issue into Proposed for the next iteration!

**Review by slimsag — APPROVED** [review]
Nice!!

EDIT: whoa, github send me a notification to review this PR 30 days late!

**Comment by abeatrix** [comment]
@slimsag GitHub knows this got put on hold 🤣

**Comment by muratsu** [comment]
@abeatrix can we close this PR and track it as an issue assigned to @jjinnii ?

**Pull request closed without merging**
